# Generated by Django 4.2 on 2023-04-09 17:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resorts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resorts",
            name="slug",
        ),
    ]
