# Generated by Django 4.2 on 2023-04-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resorts", "0004_alter_resorts_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resorts",
            name="image_four",
            field=models.ImageField(blank=True, null=True, upload_to="photos/resorts"),
        ),
        migrations.AlterField(
            model_name="resorts",
            name="image_one",
            field=models.ImageField(blank=True, null=True, upload_to="photos/resorts"),
        ),
        migrations.AlterField(
            model_name="resorts",
            name="image_three",
            field=models.ImageField(blank=True, null=True, upload_to="photos/resorts"),
        ),
        migrations.AlterField(
            model_name="resorts",
            name="image_two",
            field=models.ImageField(blank=True, null=True, upload_to="photos/resorts"),
        ),
    ]
