# Generated by Django 4.2 on 2023-04-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resorts", "0005_alter_resorts_image_four_alter_resorts_image_one_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resorts",
            name="image_one",
            field=models.ImageField(upload_to="photos/resorts"),
        ),
        migrations.AlterField(
            model_name="resorts",
            name="image_two",
            field=models.ImageField(upload_to="photos/resorts"),
        ),
    ]
