# Generated by Django 4.2 on 2023-04-14 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("resorts", "0006_alter_resorts_image_one_alter_resorts_image_two"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adventures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_name", models.CharField(max_length=200)),
                ("activity_type", models.CharField(max_length=200)),
                ("about", models.TextField()),
                ("time_take", models.CharField(max_length=200)),
                ("day_slot", models.IntegerField()),
                ("safety", models.CharField(max_length=200)),
                ("activity_one", models.ImageField(upload_to="photos/adventures")),
                ("activity_two", models.ImageField(upload_to="photos/adventures")),
                (
                    "activity_three",
                    models.ImageField(
                        blank=True, null=True, upload_to="photos/adventures"
                    ),
                ),
                (
                    "resort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resorts.resorts",
                    ),
                ),
            ],
        ),
    ]
