# Generated by Django 4.2 on 2023-04-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resorts", "0008_adventures_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="adventures",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
