# Generated by Django 4.2 on 2023-04-16 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resorts", "0010_adventures_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Destinations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=200)),
                ("spot_name", models.CharField(max_length=200)),
                ("about", models.TextField()),
                ("start_time", models.TimeField()),
                ("close_time", models.TimeField()),
                ("is_approved", models.BooleanField(default=False)),
                ("image_one", models.ImageField(upload_to="photos/destinations")),
                ("image_two", models.ImageField(upload_to="photos/destinations")),
                (
                    "image_three",
                    models.ImageField(
                        blank=True, null=True, upload_to="photos/destinations"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resorts.resorts",
                    ),
                ),
            ],
        ),
    ]
