# Generated by Django 4.2 on 2023-04-19 05:08

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):
    dependencies = [
        ("resorts", "0012_destinations_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="destinations",
            name="map_location",
            field=location_field.models.plain.PlainLocationField(
                blank=True, max_length=63, null=True
            ),
        ),
    ]
