# Generated by Django 4.2 on 2023-04-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resorts", "0014_alter_resorts_map_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="adventures",
            name="price",
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
