# Generated by Django 4.2 on 2023-04-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resorts", "0015_adventures_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="adventures",
            name="is_rejected",
            field=models.BooleanField(default=False),
        ),
    ]
