# Generated by Django 4.2 on 2023-04-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resorts", "0016_adventures_is_rejected"),
    ]

    operations = [
        migrations.AddField(
            model_name="resorts",
            name="is_rejected",
            field=models.BooleanField(default=False),
        ),
    ]
