# Generated by Django 4.2 on 2023-05-02 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resorts", "0017_resorts_is_rejected"),
        ("booking", "0002_adventurereviews_review_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DestinationReviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_heading", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("rating", models.FloatField()),
                (
                    "review_image",
                    models.ImageField(upload_to="photos/adventureReviews"),
                ),
                ("created_date", models.DateTimeField(auto_now=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resorts.destinations",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
