# Generated by Django 4.2 on 2023-05-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0006_resortpayments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resortreviews",
            name="review_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="photos/resortReviews"
            ),
        ),
    ]
